/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_josephmoscoso;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_area = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        cb_nuevoa = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jd_area2 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        cb_nuevoa1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jd_mensajes = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp_mensaje = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_e = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jb_agregar = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_salario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_jefe = new javax.swing.JComboBox<>();
        pf_pass = new javax.swing.JPasswordField();
        jb_cambioarea = new javax.swing.JButton();
        jb_despedir = new javax.swing.JButton();
        jb_ascenso = new javax.swing.JButton();
        jb_punto = new javax.swing.JButton();
        jb_broad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jb_help = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_puesto = new javax.swing.JComboBox<>();
        jb_verb = new javax.swing.JButton();
        jb_verp = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Escoja la nueva area");

        cb_nuevoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerentes de Área", "Empleados de primera linea", "Gerente general", " " }));

        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_areaLayout = new javax.swing.GroupLayout(jd_area.getContentPane());
        jd_area.getContentPane().setLayout(jd_areaLayout);
        jd_areaLayout.setHorizontalGroup(
            jd_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_areaLayout.createSequentialGroup()
                .addGroup(jd_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_areaLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jd_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_nuevoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jd_areaLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jd_areaLayout.setVerticalGroup(
            jd_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_areaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nuevoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Escoja el puesto");

        cb_nuevoa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerentes de Área", "Empleados de primera linea", "Gerente general", " " }));

        jButton2.setText("Aceptar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_area2Layout = new javax.swing.GroupLayout(jd_area2.getContentPane());
        jd_area2.getContentPane().setLayout(jd_area2Layout);
        jd_area2Layout.setHorizontalGroup(
            jd_area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_area2Layout.createSequentialGroup()
                .addGroup(jd_area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_area2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jd_area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_nuevoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_area2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel13))))
                    .addGroup(jd_area2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton2)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jd_area2Layout.setVerticalGroup(
            jd_area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_area2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nuevoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Escriba su mensaje");

        jScrollPane2.setViewportView(tp_mensaje);

        jButton3.setText("Enviar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mensajesLayout = new javax.swing.GroupLayout(jd_mensajes.getContentPane());
        jd_mensajes.getContentPane().setLayout(jd_mensajesLayout);
        jd_mensajesLayout.setHorizontalGroup(
            jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajesLayout.createSequentialGroup()
                .addGroup(jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mensajesLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel14))
                    .addGroup(jd_mensajesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mensajesLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton3)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jd_mensajesLayout.setVerticalGroup(
            jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_e.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_e.setModel(new DefaultListModel()
        );
        jScrollPane1.setViewportView(jl_e);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Organigrama");

        jb_agregar.setText("Agregar gerente/empleado");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Agregar");

        jLabel3.setText("Nombre");

        jLabel4.setText("ID empresa");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Jefe");

        jLabel7.setText("Salario");

        jLabel8.setText("Puesto");

        jb_cambioarea.setText("Cambio de area");
        jb_cambioarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cambioareaMouseClicked(evt);
            }
        });

        jb_despedir.setText("Despedir");
        jb_despedir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_despedirMouseClicked(evt);
            }
        });

        jb_ascenso.setText("Ascenso");
        jb_ascenso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ascensoMouseClicked(evt);
            }
        });

        jb_punto.setText("Punto a punto");

        jb_broad.setText("Broadcast");
        jb_broad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_broadMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Mensajes");

        jb_help.setText("Ayuda");
        jb_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_helpMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Informacion");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Administracion");

        cb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerentes de Área", "Empleados de primera linea", "Gerente general", " " }));

        jb_verb.setText("Ver Broadcast");
        jb_verb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_verbMouseClicked(evt);
            }
        });

        jb_verp.setText("Ver msj punto a punto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre)
                                .addComponent(tf_id)
                                .addComponent(tf_salario)
                                .addComponent(cb_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pf_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jb_cambioarea)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jb_ascenso)
                                                .addComponent(jb_despedir)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jb_agregar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel11)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jb_punto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jb_verp))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jb_broad)
                                    .addGap(18, 18, 18)
                                    .addComponent(jb_verb)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 221, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(172, 172, 172))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jb_help))
                            .addGap(143, 143, 143))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(142, 142, 142)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_punto)
                                    .addComponent(jb_verp))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_help))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_cambioarea)
                                    .addComponent(jb_broad)
                                    .addComponent(jb_verb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_despedir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_ascenso))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_helpMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para agregar llene los campos y presione el boton Agregar gerente/empleado"
                + "\nPara cambiar de area seleccione en la lista y luego haga click en el boton Cambio de area"
                + "\nPara despedir a alguien seleccione en la lista y luego haga click en el boton Despedir"
                + "\nPara Ascender a alguien seleccione en la lista y luego haga click en el boton Ascenso"
                + "\nPara enviar un mensaje punto a punto seleccione en la lista y luego haga click en el boton Punto a punto"
                + "\nPara enviar un Broadcast seleccione en la lista y luego haga click en el boton Broadcast");
    }//GEN-LAST:event_jb_helpMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        // TODO add your handling code here:
        try {
            DefaultListModel m = (DefaultListModel) jl_e.getModel();
            empleado x = new empleado(tf_nombre.getText(), tf_id.getText(), pf_pass.getText(), (String) cb_jefe.getSelectedItem(), Integer.parseInt(tf_salario.getText()), (String) cb_puesto.getSelectedItem());
            cb_jefe.addItem(x.toString());
            m.addElement(x);
            tf_nombre.setText("");
            tf_id.setText("");
            tf_salario.setText("");
            pf_pass.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dato incorrecto, ingrese otra vez por favor");
        }

    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_cambioareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cambioareaMouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                jd_area.setModal(true);
                jd_area.pack();
                jd_area.setLocationRelativeTo(this);
                jd_area.setVisible(true);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jb_cambioareaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                DefaultListModel m = (DefaultListModel) jl_e.getModel();
                empleado x;
                x = (empleado) m.get(jl_e.getSelectedIndex());
                x.setPuesto((String) cb_nuevoa.getSelectedItem());
                m.setElementAt(x, jl_e.getSelectedIndex());
                JOptionPane.showMessageDialog(this, "Datos modificados con exito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error, no se pudo editar");
            // e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_despedirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_despedirMouseClicked
        // TODO add your handling code here:
        try {
            DefaultListModel m = (DefaultListModel) jl_e.getModel();
            if (jl_e.getSelectedIndex() >= 0) {
                m.removeElementAt(jl_e.getSelectedIndex());
                JOptionPane.showMessageDialog(this, "Persona despedida con exito");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_despedirMouseClicked

    private void jb_ascensoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ascensoMouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                jd_area2.setModal(true);
                jd_area2.pack();
                jd_area2.setLocationRelativeTo(this);
                jd_area2.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_ascensoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                DefaultListModel m = (DefaultListModel) jl_e.getModel();
                empleado x;
                x = (empleado) m.get(jl_e.getSelectedIndex());
                x.setPuesto((String) cb_nuevoa.getSelectedItem());
                m.setElementAt(x, jl_e.getSelectedIndex());
                JOptionPane.showMessageDialog(this, "Datos modificados con exito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error, no se pudo editar");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_broadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_broadMouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                jd_mensajes.setModal(true);
                jd_mensajes.pack();
                jd_mensajes.setLocationRelativeTo(this);
                jd_mensajes.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_broadMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            if (jl_e.getSelectedIndex() >= 0) {
                DefaultListModel m = (DefaultListModel) jl_e.getModel();
                empleado x;
                x = (empleado) m.get(jl_e.getSelectedIndex());
                archivo(x);
            }
            JOptionPane.showMessageDialog(this, "Mensaje mandado con exito");
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error, no se pudieron mandar mensajes");
        }
    }//GEN-LAST:event_jButton3MouseClicked
    public void archivo(empleado x) throws IOException {
        b.add(new mensajes(x.getNombre(), x.getJefe(), "no", tp_mensaje.getText()));
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Lab8_JosephMoscoso2/mensajes.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            // bw.newLine();
            bw.write(b.get(b.size()-1).toString() + ";");
            bw.newLine();
            bw.flush();
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }
    private void jb_verbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_verbMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jb_verbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_jefe;
    private javax.swing.JComboBox<String> cb_nuevoa;
    private javax.swing.JComboBox<String> cb_nuevoa1;
    private javax.swing.JComboBox<String> cb_puesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_ascenso;
    private javax.swing.JButton jb_broad;
    private javax.swing.JButton jb_cambioarea;
    private javax.swing.JButton jb_despedir;
    private javax.swing.JButton jb_help;
    private javax.swing.JButton jb_punto;
    private javax.swing.JButton jb_verb;
    private javax.swing.JButton jb_verp;
    private javax.swing.JDialog jd_area;
    private javax.swing.JDialog jd_area2;
    private javax.swing.JDialog jd_mensajes;
    private javax.swing.JList<String> jl_e;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_salario;
    private javax.swing.JTextPane tp_mensaje;
    // End of variables declaration//GEN-END:variables
    ArrayList<mensajes> b = new ArrayList();
    ArrayList<mensajes> p = new ArrayList();
}
